name: Deploy to NuxtHub
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy to NuxtHub'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: frontend/src

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/src/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: portfolio-89n8
          directory: frontend/src
        env:
          NUXT_TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          NUXT_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
